version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: medium_clone_db
    environment:
      POSTGRES_DB: medium_clone
      POSTGRES_USER: medium_clone
      POSTGRES_PASSWORD: medium_clone
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./back
    container_name: medium-clone-backend
    environment:
      DATABASE_URL: postgres://medium_clone:medium_clone@postgres:5432/medium_clone
    depends_on:
      - postgres
    ports:
      - "3001:3001"

#  frontend:
#    build:
#      context: ./front
#    container_name: medium_clone_frontend
#    depends_on:
#      - backend
#    ports:
#      - "3000:3000"

volumes:
  postgres_data:
